= Changelog

This page lists changes to the Change Data Capture feature in different versions of Neo4j.

== Version 5.15
=== Updated features
[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]

Updated details around logical keys in node entities to handle multiple key constraints on the same label
a|
The structure for node keys has changed from
[source, json, role="noheader"]
----
{
  "keys": {
    "Person": {
      "prop1" : 1,
      "prop2" : 2.0,
      "prop3" : "3"
    }
  }
}
----
to
[source, json, role="noheader"]
----
{
  "keys": {
    "Person": [
      {
        "prop1" : 1,
        "prop2" : 2.0
      },
      {
        "prop3" : "3"
      }
    ]
  }
}
----
a|
label:functionality[]
label:new[]

Updated details around logical keys in relationship entities to handle multiple key constraints on the same type
a|
The structure for node keys has changed from
[source, json, role="noheader"]
----
{
  "keys": {
    "prop1" : 1,
    "prop2" : 2.0,
    "prop3" : "3"
  }
}
----
to
[source, json, role="noheader"]
----
{
  "keys": [
    {
      "prop1" : 1
    },
    {
      "prop2" : 2.0,
      "prop3" : "3"
    }
  ]
}
----
|===

== Version 5.13
=== Updated features
[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CALL cdc.query(selectors=[
    {
        select: "e",
        authenticatedUser: "alice",
        executingUser: "bob",
        txMetadata: { specialId: 42 }
    }
])
----
a|
The CDC query procedure `cdc.query` can now use metadata selectors for each of the entity selection types (e,n,r). The 3 options available are:

 - txMetadata: key/value pairs to match on
 - executingUser: the user that executed the transaction
 - authenticatedUser: the authenticated user that executed the transaction (may be different to executingUser when performing user impersonation)
|===

== Version 5.10
=== New features
[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]

Cluster support
a|
CDC is now available in cluster environments
|===