= Changelog

This page lists changes to the Change Data Capture feature in different versions of neo4j.

== Version 5.13
=== Updated features
[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:updated[]

Feature flag enabled by default
a|
The `internal.dbms.change_data_capture` feature flag has been enabled by default and no longer needs to be set by users. Users still need to xref:getting-started/enrichment-mode.adoc[enable transaction log enrichment] for each database that they want to use CDC with.

a|
label:functionality[]
label:new[]
[source, cypher, role="noheader"]
----
CALL cdc.query(selectors=[
    {
        select: "e",
        authenticatedUser: "alice",
        executingUser: "bob",
        txMetadata: { specialId: 42 }
    }
])
----
a|
The CDC query procedure `cdc.filtered.query` can now use metadata selectors for each of the entity selection types (e,n,r). The 3 options available are:

 - txMetadata: key/value pairs to match on
 - executingUser: the user that executed the transaction
 - authenticatedUser: the authenticated user that executed the transaction (may be different to executingUser when performing user impersonation)
|===

== Version 5.10
=== New features
[cols="2", options="header"]
|===
| Feature
| Details

a|
label:functionality[]
label:new[]

Cluster support
a|
CDC is now available in cluster environments
|===