[[troubleshooting]]
= Troubleshooting
:description: This chapter describes common change data capture related errors.

You can find a list of error codes and causes that are used by change data capture procedures.

== Error codes

=== Neo.DatabaseError.ChangeDataCapture.Disabled

Change data capture is currently disabled for this database.
You need to enable xref:getting-started/enrichment-mode.adoc[log enrichment] to make use of change data capture procedures.

=== Neo.DatabaseError.ChangeDataCapture.ScanFailure

We cannot find the transaction log entry for the change identifier provided.
This is likely because of your xref:getting-started/key-considerations.adoc#log-retention[log retention] settings.
Please review your settings and increase the log retention period to fit your requirements.

=== Neo.ClientError.ChangeDataCapture.InvalidIdentifier

The change identifier provided is invalid and could be due to one of the following reasons:

 - it was generated by another CDC-enabled database
 - the identifier had an invalid version/format
 - the transaction pointed to via the identifier does not exist or could not be found in the current transaction log files
 - the transaction ID / commit timestamp pairing does not match that in the database's transaction log files

Verify that the change identifier you've provided is acquired from either of xref:procedures/earliest.adoc[db.cdc.earliest], xref:procedures/current.adoc[db.cdc.current] or xref:procedures/query.adoc[db.cdc.query] procedures for this database.