= Troubleshooting
:description: This chapter describes common change data capture related errors.

This page contains a list of CDC error codes together with their likely causes.


== Error codes

=== Neo.DatabaseError.ChangeDataCapture.Disabled

Change data capture is currently disabled for this database.
You need to enable CDC to make use of CDC procedures, see xref:get-started/self-managed.adoc[].


=== Neo.DatabaseError.ChangeDataCapture.ScanFailure

CDC cannot find the transaction log entry for the change identifier provided.
This is likely because of your xref:get-started/self-managed.adoc#log-retention[log retention] settings.
Review your settings and increase the log retention period to fit your requirements.


=== Neo.ClientError.ChangeDataCapture.InvalidIdentifier

The provided change identifier is invalid.
That could be due to one of the following reasons:

- it was generated by another database
- the identifier had an invalid version/format
- the transaction to which the identifier points to does not exist or can not be found in the current transaction log files
- the transaction ID / commit timestamp pairing does not match that in the database's transaction log files
- the database was restored from a previous snapshot, see xref:backup-restore.adoc[]

Verify that the change identifier you have provided is acquired from either of xref:procedures/index.adoc#earliest[db.cdc.earliest], xref:procedures/index.adoc#current[db.cdc.current] or xref:procedures/index.adoc#query[db.cdc.query] procedures for this database.
