= Documentation for CDC

This repo contains the files that you need to work with the CDC docs.
There are two branches: `main` and `dev`.
`main` reflects the current docs and `dev` should reflect the current docs plus any work to go in to the next release.
All PRs should be raised against `dev` and if applicable, cherry-picked to `main`.
Merged PRs against `main` are published automatically.

The examples in this repo have a separate repo with executable variants:
https://github.com/neo-technology/cdc-documentation-examples

Upon release of a minor version, the `dev` branch is merged into the `main` branch.

== Prereqs

- link:https://nodejs.org/en/download/[Node.js]
- npm

== Installation

To install the required packages:

----
npm i
----

== Generating HTML output

To convert asciidoc source to HTML:

----
npm run build
----

== Viewing HTML output

To view the built site, launch a local server:

1. `npm start`
2. In a browser tab, go to `localhost:8000`

== Live preview

When you run `npm start`, the project is monitored for updates to asciidoc files.

If a change to an asciidoc file is detected the site is automatically rebuilt.
