[[key-considerations]]
= Key considerations

== Disk size

Enabling change data capture on a database causes more data to be written into transaction log files.
This means that the log files are rotated more frequently and log pruning is activated sooner (based on your configuration).
The disk may run out of space if the disk size for transaction log storage is limited.
Please ensure that you have plenty of available space.

[IMPORTANT]
====
Please allow for a 50% increase in data written to the transaction log with `DIFF` log enrichment mode, and 75% for `FULL` log enrichment mode.
Actual disk usage depends on the application, data model and transaction characteristics.
The impact on log growth should be evaluated during the EAP.
====

[#_using_cdc_with_existing_databases]
== Using CDC with existing databases

You can enable log enrichment on existing databases in order to be able to track changes.
However, enabling log enrichment affects only future transactions and existing data will not be surfaced by CDC procedures.
If your use case requires a snapshot of existing data for CDC purposes, best practice is to;

* Enable log enrichment with one of the desired values
* Set database to read-only
* Capture current change identifier
* Perform a snapshot using an application of your own that reads all nodes and relationships of interest and process those according to your CDC requirements
* Set database to read-write
* Run your CDC application starting with the captured change identifier

[[log-retention]]
== Transaction log retention

Since Neo4j stores change data capture information inside transaction log entries, it is important that you configure your transaction log retention period based on your requirements.
It is recommended to configure the `db.tx_log.rotation.retention_policy` setting using temporal types, such as `hours` or `days`.


The number of hours or days to keep transaction logs is highly dependent on your CDC use case, but as a general rule of thumb you can pick the period based on downtime tolerance of your downstream application so that the changes you have not yet processed are not pruned.

For more details on transaction log retention and how to configure it, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/transaction-logs/#transaction-logging-log-retention[Operations Manual -> Configuration -> Transaction Log].

[[cursor-management]]
== Cursor management and server side filtering
The changeId returned from xref:procedures/earliest.adoc[db.cdc.earliest], xref:procedures/current.adoc[db.cdc.current] and xref:procedures/query.adoc[db.cdc.query] are valid until Neo4j performs transaction log rotation as discussed in the previous section.

Usually the cursor stays valid, since each call to `db.cdc.query` updates the cursor.

Very strict selectors may, however, cause `db.cdc.query` to not return any changes.
This can in extreme cases lead to the cursor not being updated in time before transaction log rotation.
To avoid this, the xref:examples/index.adoc[examples] in this documentation update the cursor to `db.cdc.current` if `db.cdc.query` returns empty.
Note that `db.cdc.current` needs to be called and stored before `db.cdc.query` for this to work.

Another way to avoid this issue is to use broader selectors and perform client side filtering instead.

[[restore-from-backup]]
== Backup and restore operations

[WARNING]
====
Restoring your Neo4j database from a backup is likely to cause *loss of data and corrupted data in your CDC application*.
Read the following sections carefully if you are using CDC and intend to restore your database from backup.
====

=== Loss of change events
The Neo4j restore procedures replace the existing database with a *new* database.
This database has a new transaction log and any change identifier (cursor) generated from the old transaction log is not usable with the new database.
Furthermore, it is essential that the transaction log retention setting of the restored database matches that of your existing database.

The following steps outline how to mitigate this issue:

[NOTE]
====
The steps outlined here ensure that all change events are transmitted to your CDC application.
Depending on your application, these change events might still be unexpected and cause further issues.
See xref:_unexpected_change_events[the following section], before performing these steps.
====

. *Set the database into read only mode.* +
This prevents any new changes coming through.

. *Take note of the `txLogEnrichment` value of your database.* +
The options column of `SHOW DATABASES YIELD name, options` shows the transaction log enrichment value.
. *Verify that your CDC application is caught up and has consumed all changes in the database.*
. *Stop your CDC application.*
. *Restore your database from backup.*
. *Set the restored database into read-only mode.*
. *Ensure that the restored database has the same `txLogEnrichment` value as your existing database.* +
Compare the output of `SHOW DATABASES YIELD name, options` with the value noted in step 2.
If necessary update the value using the `ALTER DATABASE` command (link:{neo4j-docs-base-uri}/operations-manual/{page-version}/database-administration/standard-databases/manage-databases#alter-database-options[Operations Manual -> Database administration -> Standard databases -> Managing Databases -> Alter database options]).
. *Restart your CDC application, using xref:procedures/earliest.adoc[db.cdc.earliest] as the starting cursor.*
. *Enable writes to the restored database.*
. *Verify that changes are consumed as by your CDC application.*

[#_unexpected_change_events]
=== Unexpected change events
When restoring a Neo4j database to a previous snapshot, the changes that have happened since the snapshot was taken are effectively reverted on the database.
There is no process for letting your CDC application know that these changes 'never happened'.
New changes on the restored database are changes compared to the state that the database had when the snapshot was taken.
Effectively, your CDC application expects certain changes to have happened that according to your Neo4j database "never happened".

Some examples of problematic scenarios are:

. *Entities being created 'a second time'* +
A node/relationship created between the snapshot and restore operation exists in your CDC application but not in the Neo4j database.
If the node/relationship is (re-)created in your Neo4j database, your CDC application sees a duplicate node/relationship.

. *'Missing' entities* +
A node/relationship that was dropped between the snapshot and restore operation does not exist in your CDC application but does now exist in the Neo4j database (again).
If the node/relationship is updated, your CDC application sees an update to a previously deleted entity.

. *Out of sync attributes* +
Changes on attributes may have been rolled back in the restore operation.
For example, a `Movie` node in your Neo4j database may have a rating of 5 stars, whereas the latest change that your CDC application consumed changed the rating from 5 stars to 3 stars.
Which could cause the two systems to treat the node differently.

If your CDC application relies on an internal state it is likely required to restore the state of your CDC application as if it was working with a new database with existing data. For details on this process read the xref:_using_cdc_with_existing_databases[relevant section above].

=== Inconsistent elementId
The elementId returned by `db.cdc.query` is not guaranteed to be stable across operations that change the underlying database.
After restoring from backup, new changes to existing elements are published under a new elementId.

Neo4j recommends that logical / business keys are used to identify elements instead of elementId.
See xref:getting-started/constraints.adoc#change-data-capture-constraints[Capturing Key Properties] for details on logical / business keys.

[[non-tx-log-changes]]
== Unrecorded changes

CDC can only capture data changes that pass through the transaction layer and any data creation that avoids this layer can therefore not be captured.
For example, when importing data with the link:{neo4j-docs-base-uri}/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/[`neo4j-admin database import`] tool, whether full or incremental, or when loading data with the link:{neo4j-docs-base-uri}/operations-manual/current/backup-restore/restore-dump/[`neo4j-admin database load`] tool, data is written directly to the store without sending anything to the transaction logs and therefore, such changes are **not** captured by CDC.