[quick-start]
= Quick start

The following section describes the basic steps to enable and use CDC.

[NOTE]
====
It is recommended to read the section about xref:getting-started/security.adoc[] as well as xref:getting-started/key-considerations.adoc[] before proceeding.
====

== Enable transaction log enrichment on the database
Follow the instructions in xref:getting-started/enrichment-mode.adoc#modifying_enrichment_mode[Enrichment mode -> Modifying enrichment mode] to set enrichment mode. 
In Aura, enrichment mode is managed through the Aura Console UI.

Once enrichment mode is set to either `FULL` or `DIFF`, the database is ready to answer CDC queries.

== Client application
See xref:examples/index.adoc[] for more information on what a typical CDC application would look like and xref:procedures/index.adoc[] for a detailed explanation of the procedures used.

See xref:getting-started/constraints.adoc[] for details on how to use business keys to identify changes and  xref:selectors/index.adoc[] for information on how the CDC output can be filtered.