[[security]]
= Security
:description: Security considerations when using CDC.

CDC returns all changes in the database and is not limited to the entities which a certain user is allowed to access.
In order to prevent unauthorized access, the procedure xref:procedures/query.adoc[`db.cdc.query`] requires admin privileges and should be configured for least privilege access.

For a regular user to be able to run `db.cdc.query`, the user must have been granted execute privileges as well as boosted execute privileges.
[source, cypher]
----
GRANT EXECUTE PROCEDURE db.cdc.query ON DBMS TO $role
GRANT EXECUTE BOOSTED PROCEDURE db.cdc.query ON DBMS TO $role
----

[NOTE]
====
Non-Boosted execute privileges are usually part of the `PUBLIC` role in which case they do not need to be granted a second time.
====

Furthermore, the user will not have access to a database unless they have been granted access.
[source, cypher]
----
GRANT ACCESS ON DATABASE $database TO $role
----
[NOTE]
====
Usually The `PUBLIC` role already has access to the default database.
====

The procedures xref:procedures/current.adoc[db.cdc.current] and xref:procedures/earliest.adoc[db.cdc.earliest] do not require admin privileges. In order to execute these, access to the database and regular execution privileges are sufficient.

For more details regarding procedure privileges in Neo4j, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization/manage-execute-permissions[Operations Manual -> Manage procedure and user-defined function permissions].