= CDC on self-managed instances


include::partial$get-started.adoc[tags=intro]


[[tweak-mode]]
== Toggle CDC mode

=== Create a database with CDC enabled

To create a new database with CDC enabled, use the link:https://www.neo4j.com/docs/operations-manual/current/database-administration/standard-databases/manage-databases/#manage-databases-create[`CREATE DATABASE`] Cypher command and set the option `txLogEnrichment` to either `FULL` or `DIFF`.

.Query
[source, cypher]
----
CREATE DATABASE <dbName> IF NOT EXISTS OPTIONS {txLogEnrichment: "FULL"}
----

=== Modify a database's CDC mode

To tweak the CDC mode on an existing database, use the https://www.neo4j.com/docs/operations-manual/current/database-administration/standard-databases/manage-databases/#administration-databases-alter-database[`ALTER DATABASE`] Cypher command and set the option `txLogEnrichment` to either `FULL` or `DIFF`.

.Query
[source, cypher]
----
ALTER DATABASE <dbName> SET OPTION txLogEnrichment "DIFF"
----

[IMPORTANT]
====
Modifying CDC mode from `DIFF` to `FULL` or viceversa immediately changes the  xref:procedures/output-schema.adoc[structure of captured changes].
Your CDC application must be able to deal with the change of format.
====

[[get-cdc-mode]]
=== Get a database's CDC mode

To see what value the CDC mode of a database is, use the link:https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/manage-databases/#manage-databases-list[`SHOW DATABASES`] Cypher command.

.Query
[source, cypher]
----
SHOW DATABASES YIELD name, options
----


.Result
[role="queryresult",options="header,footer",cols="1m,1m"]
|===
| name | options

| "neo4j"
| {"txLogEnrichment": "DIFF"}


| "system"
| {}

|===


=== Disable CDC

To disable CDC on a database, either set `txLogEnrichment` explicitly to `OFF` or remove it altogether.

.Using set option clause
[source, cypher]
----
ALTER DATABASE <dbName> SET OPTION txLogEnrichment "OFF"
----

.Using remove option clause
[source, cypher]
----
ALTER DATABASE <dbName> REMOVE OPTION txLogEnrichment
----

[WARNING]
====
Disabling CDC immediately breaks the continuity of change events.
**Change identifiers generated before disabling can no longer be used and, even if CDC is re-enabled, the previously-generated change identifiers remain invalid.**
Disabling and then re-enabling CDC is equivalent to enabling it for the first time: there is no memory of previous changes.
====


[[key-considerations]]
== Key considerations


[[security]]
=== Security

include::partial$get-started.adoc[tags=security]


[[disk-size]]
=== Disk size

Enabling change data capture on a database causes more data to be written into transaction log files.
This means that the log files are rotated more frequently and log pruning is activated sooner (based on your configuration).
The disk may run out of space if the disk size for transaction log storage is limited, so ensure that you have plenty of available space.

In particular, **plan for a 50% increase in data written to the transaction log with `DIFF` CDC mode, and 75% for `FULL` CDC mode.**
Actual disk usage depends on the application, data model and transaction characteristics.


[[log-retention]]
=== Transaction log retention

Since CDC information is stored in transaction log entries, the time for which the logs are retained dictates how much back in time your application may query for CDC data.

The number of hours or days to keep the transaction log depends on your use case, but as a general rule of thumb you can pick a period greater or equal to the downtime tolerance of your downstream application, so that the changes don't get pruned before the application has had time to process them.

.Transaction log configuration and CDC behavior
====
This example shows the behavior that results from a given configuration.

`db.tx_log.rotation.size = 256M` +
`db.tx_log.rotation.retention_policy = 2G 1Day` +
`db.checkpoint.interval.time = 15m` +
`db.checkpoint.interval.tx = 100000`

As new transactions come in, the server writes them to a log file. When that file exceeds 256MB, it creates a new file and continues writing there (transactions are never broken across files though, so if the current log is 255MB when a new 5MB transaction comes in, the file will grow to 260MB before rotating to a new file).

Every 15 minutes _or_ 100000 transactions (whichever happens first), the server goes through the transaction log files from newer to oldest.
When the sum of the scanned files is greater than 2GB, all subsequent files are deleted, including the latest scanned one, so that the total size is again below 2GB.
Files older than 1 day are also deleted.

In other words, the server keeps _at most_ 2GB worth of transaction logs, as long as they are all more recent than 1 day.
As long as they are all more recent than 1 day, the server keeps _at least_ `2GB - 256MB` worth of transaction logs (256MB are always needed for the current log file to grow into).
In case large transactions resulted in log files larger than 256MB, the minimum retained size of logs may be smaller than `2GB - 256MB`.
====

For more details on transaction log files and how to configure them, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/transaction-logs/[Transaction logging].


[[non-tx-log-changes]]
=== Unrecorded changes

CDC can only capture data changes that pass through the transaction layer and any data creation that avoids this layer can therefore not be captured.
For example, when importing data with the link:{neo4j-docs-base-uri}/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/[`neo4j-admin database import`] tool, whether full or incremental, or when loading data with the link:{neo4j-docs-base-uri}/operations-manual/current/backup-restore/restore-dump/[`neo4j-admin database load`] tool, data is written directly to the store without sending anything to the transaction log, so such changes are **not** captured by CDC.
