tag::intro[]

Neo4j extracts CDC information from the transaction log.
However, by default the transaction log does not contain information directly usable by CDC.
For CDC to work, the transaction log need to be _enriched_ with further information.
This is applied as an extra configuration option to each database.
As soon as CDC is enabled, the database is ready to answer CDC queries from xref:examples/index.adoc[client applications].

CDC has three working modes:

- `OFF` -- CDC is disabled (default).
- `DIFF` -- Changes are captured as the difference between before and after states of each changed entity (i.e. they only contain removals, updates and additions).
- `FULL` -- Changes are recorded as a complete copy of the before and after states of each changed entity (i.e. the contain the full node/relationship, regardless of the extent to which they were altered).

end::intro[]


tag::security[]

CDC returns all changes in the database and is not limited to the entities which a certain user is allowed to access.
In order to prevent unauthorized access, the procedure xref:procedures/index.adoc#query[`db.cdc.query`] requires admin privileges and should be configured for least privilege access.

For a regular user to be able to run `db.cdc.query`, the user must have been granted execute privileges as well as boosted execute privileges.

[source, cypher]
----
GRANT EXECUTE PROCEDURE db.cdc.query ON DBMS TO $role;
GRANT EXECUTE BOOSTED PROCEDURE db.cdc.query ON DBMS TO $role;
----

[NOTE]
====
Non-boosted execute privileges are usually part of the `PUBLIC` role, in which case they do not need to be granted a second time.
====

Furthermore, the user does not have access to a database unless they have been granted access.

[source, cypher]
----
GRANT ACCESS ON DATABASE $database TO $role
----

[NOTE]
====
Usually the `PUBLIC` role already has access to the default database.
====

The procedures xref:procedures/index.adoc#current[`db.cdc.current`] and xref:procedures/index.adoc#earliest[`db.cdc.earliest`] do not require admin privileges. In order to execute these, access to the database and regular execution privileges are sufficient.

For more details regarding procedure privileges in Neo4j, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization/manage-execute-permissions[Operations Manual -> Manage procedure and user-defined function permissions].

end::security[]
