[[change-data-capture-querying-changes]]
= Querying changes

The procedure `db.cdc.query` is used to query the database for captured changes.
Once all changes have been streamed the query terminates.

[NOTE]
====
Since the transaction logs get pruned regularly, changes are only available for querying as long as they have not been pruned.
See link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/transaction-logs/#transaction-logging-log-pruning[Operations Manual -> Configuration -> Transaction Log] for more details.

Changes also stop being available if xref:getting-started/enrichment-mode.adoc[enrichment mode] is disabled.
Even if enabled again, it is not possible to query the previous change records.
====

.Signature
[source]
----
db.cdc.query(
    from =  :: STRING?, // <1>
    selectors = [] :: LIST? OF MAP? // <2>
) :: (
    id :: STRING?, // <3>
    txId :: INTEGER?, // <4>
    seq :: INTEGER?, // <5>
    metadata :: MAP?, // <6>
    event :: MAP? // <7>
) 
----

<1> The change identifier, either captured from an earlier call to `db.cdc.query` or from one of `db.cdc.current` or `db.cdc.earliest`, to query the captured changes from.
Default value is `""` (empty string) which is replaced with `db.cdc.current` implicitly.
This value is treated as exclusive and the results of the query do not include the change corresponding to this value.
To get a `from` value for the first iteration, see xref:procedures/current.adoc[db.cdc.current] and xref:procedures/earliest.adoc[db.cdc.earliest].
<2> An optional list of selectors that could be used to filter out changes.
Default is an empty list, which means _all_ changes are returned without any filtering taking place.
See xref:selectors/index.adoc[selectors] for details.
<3> A unique change identifier that identifies each change record.
Used as a cursor to continue querying changes from last processed change.
<4> A number identifying which transaction the change happened in, unique in combination with `seq`.
Transaction identifiers are not continuous.
Some transactions, such as system and schema commands, are not recorded in change data capture and cause gaps in the transaction identifiers.
<5> A number used for ordering changes happened in the same transaction.
Note that the order of changes observed in the output does not necessarily correspond to the order of changes applied during the transaction.
<6> A map of values that contain metadata information about the transaction.
This is the same for all of the changes in a single transaction.
For a detailed description of metadata fields, see xref:procedures/output-schema.adoc[].
<7> A set of information describing the change on the entity.
For a detailed description of change event, see xref:procedures/output-schema.adoc[].

====
.Query for changes
[source, cypher]
----
CALL db.cdc.query("A3V16ZaLlUmnipHLFkWrlA0AAAAAAAAABAAAAAAAAAAA")
----

.Result
[role="queryresult",options="header,footer",cols="5*<m"]
|===
| +id+ | +txId+ | +seq+ | +metadata+ | +event+
| +"A3V16ZaLlUmnipHLFkWrlA0AAAAAAAAABQAAAAAAAAAA"+ | +4+ | +0+ | +{executingUser: "neo4j", connectionClient: "127.0.0.1:63783", authenticatedUser: "neo4j", captureMode: "DIFF", serverId: "4c453340", databaseId: ""edec6ba8-e82f-4aac-ae41-2725f2357fdd", connectionType: "bolt", connectionServer: "127.0.0.1:7687", txStartTime: 2023-04-25T07:50:10.250Z, txCommitTime: 2023-04-25T07:50:10.305Z}+ | +{elementId: "4:7575e996-8b95-49a7-8a91-cb1645ab940d:0", keys: {}, eventType: "n", state: {before: NULL, after: {properties: {}, labels: []}}, operation: "c", labels: []}+

5+d|Rows: 1
|===

For a full description of change record schema, see xref:procedures/output-schema.adoc[].
====